"use client";
import { useEffect, useState, type FormEvent } from "react";
import type { Role } from "./sections";

const API=process.env.NEXT_PUBLIC_API_URL??"http://localhost:4000";
type Lecture={id:string;title:string;description:string;content_url:string;created_at:string};
type Course={id:string;code:string;title:string;department:string;academic_year:number;semester:number;teacher:{name:string}|null;lectures:Lecture[];_count:{members:number}};
type Notice={id:string;title:string;body:string;priority:string;expires:string;author_name:string;course:{code:string;title:string}|null};
type PortalData={user:{name:string;role:Role;department:string|null;academic_year:number|null;semester:number|null};courses:Course[];announcements:Notice[];metrics:{courses:number;announcements:number;university_events:number;users:number}};
async function request<T>(path:string,options?:RequestInit){const token=localStorage.getItem("campus_token");const response=await fetch(API+path,{...options,headers:{"Content-Type":"application/json",Authorization:`Bearer ${token}`,...options?.headers}});const body=await response.json();if(!response.ok)throw new Error(body.error??"Request failed");return body as T}

export default function CohortDashboard({role,notify}:{role:Role;notify(message:string):void}){
 const [data,setData]=useState<PortalData|null>(null),[error,setError]=useState(""),[busy,setBusy]=useState(false),[lectureCourse,setLectureCourse]=useState<Course|null>(null),[announcement,setAnnouncement]=useState(false);
 async function load(){try{setData(await request<PortalData>("/portal/dashboard"));setError("")}catch(reason){setError((reason as Error).message)}}
 useEffect(()=>{void load()},[role]);
 if(error)return <div className="sectionError">! {error}</div>;
 if(!data)return <div className="loading"><span/><p>Loading your secure dashboard…</p></div>;
 const cohort=data.user.department?`${data.user.department} · Year ${data.user.academic_year} · Semester ${data.user.semester}`:"University-wide access";
 return <div className="cohortDashboard"><div className="roleHero"><div><small>{role.toUpperCase()} CONTROL ROOM</small><h2>{data.user.name}</h2><p>{cohort}</p></div><div className="roleMetrics"><span><b>{data.metrics.courses}</b>Courses</span><span><b>{data.metrics.announcements}</b>Notices</span><span><b>{data.metrics.university_events}</b>University events</span>{role==="admin"&&<span><b>{data.metrics.users}</b>Users</span>}</div></div>
 {role==="admin"&&<div className="roleNotice">Admin controls university-wide events from the Events section. Course creation, teacher assignment, and student enrollment are protected by admin-only API endpoints.</div>}
 <section className="dashboardBlock"><div className="sectionTools"><div><h2>{role==="teacher"?"My teaching courses":role==="admin"?"All course offerings":"My assigned courses"}</h2><p>Only courses assigned to this authenticated account are shown.</p></div></div>{data.courses.length?<div className="courseCards">{data.courses.map(course=><article key={course.id}><div><small>{course.department} · YEAR {course.academic_year} · SEM {course.semester}</small><h3>{course.code}</h3><p>{course.title}</p></div><span>Teacher: <b>{course.teacher?.name??"Not assigned"}</b></span><span>{course._count.members} enrolled students</span>{course.lectures.length?<div className="lectureList">{course.lectures.map(item=><a key={item.id} href={item.content_url} target="_blank" rel="noreferrer"><b>{item.title}</b><small>{item.description||"Lecture material"}</small></a>)}</div>:<small>No lecture content yet.</small>}{(role==="teacher"||role==="admin")&&<button className="newButton" onClick={()=>setLectureCourse(course)}>+ Upload lecture link</button>}</article>)}</div>:<div className="blank"><h2>No assigned courses</h2><p>An administrator must assign this account to a course in the matching cohort.</p></div>}</section>
 <section className="dashboardBlock"><div className="sectionTools"><div><h2>Cohort announcements</h2><p>Visible only to matching department, year, semester, and assigned course students.</p></div>{(role==="representative"||role==="admin")&&<button className="newButton" onClick={()=>setAnnouncement(true)}>+ Publish announcement</button>}</div>{data.announcements.length?<div className="cohortNotices">{data.announcements.map(item=><article key={item.id}><em className={item.priority}>{item.priority}</em><div><small>{item.course?`${item.course.code} · ${item.course.title}`:"WHOLE COHORT"}</small><h3>{item.title}</h3><p>{item.body}</p><span>By {item.author_name} · expires {item.expires}</span></div></article>)}</div>:<div className="blank"><p>No active announcements for your cohort and courses.</p></div>}</section>
 {lectureCourse&&<LectureForm course={lectureCourse} busy={busy} close={()=>setLectureCourse(null)} submit={async value=>{setBusy(true);try{await request(`/portal/courses/${lectureCourse.id}/lectures`,{method:"POST",body:JSON.stringify(value)});await load();setLectureCourse(null);notify("Lecture content published")}catch(reason){setError((reason as Error).message)}finally{setBusy(false)}}}/>} 
 {announcement&&<AnnouncementForm courses={data.courses} busy={busy} close={()=>setAnnouncement(false)} submit={async value=>{setBusy(true);try{await request("/portal/announcements",{method:"POST",body:JSON.stringify(value)});await load();setAnnouncement(false);notify("Cohort announcement published")}catch(reason){setError((reason as Error).message)}finally{setBusy(false)}}}/>}</div>
}
function LectureForm({course,busy,close,submit}:{course:Course;busy:boolean;close():void;submit(value:{title:string;description:string;content_url:string}):void}){const [title,setTitle]=useState(""),[description,setDescription]=useState(""),[content_url,setUrl]=useState("");return <div className="backdrop"><form className="modal" onSubmit={(event:FormEvent)=>{event.preventDefault();submit({title,description,content_url})}}><div className="modalTitle"><div><small>{course.code}</small><h2>Publish lecture content</h2></div><button type="button" onClick={close}>×</button></div><div className="formGrid"><label>Title<input required value={title} onChange={e=>setTitle(e.target.value)}/></label><label>Content URL<input required type="url" value={content_url} onChange={e=>setUrl(e.target.value)}/></label><label className="wide">Description<textarea value={description} onChange={e=>setDescription(e.target.value)}/></label></div><div className="modalActions"><button type="button" onClick={close}>Cancel</button><button className="newButton" disabled={busy}>Publish</button></div></form></div>}
function AnnouncementForm({courses,busy,close,submit}:{courses:Course[];busy:boolean;close():void;submit(value:{title:string;body:string;priority:string;expires:string;course_id:string|null}):void}){const [title,setTitle]=useState(""),[body,setBody]=useState(""),[priority,setPriority]=useState("medium"),[expires,setExpires]=useState(new Date(Date.now()+30*864e5).toISOString().slice(0,10)),[courseId,setCourseId]=useState("");return <div className="backdrop"><form className="modal" onSubmit={(event:FormEvent)=>{event.preventDefault();submit({title,body,priority,expires,course_id:courseId||null})}}><div className="modalTitle"><div><small>SCOPED DELIVERY</small><h2>Publish announcement</h2></div><button type="button" onClick={close}>×</button></div><div className="formGrid"><label>Title<input required value={title} onChange={e=>setTitle(e.target.value)}/></label><label>Course<select value={courseId} onChange={e=>setCourseId(e.target.value)}><option value="">Whole cohort</option>{courses.map(course=><option value={course.id} key={course.id}>{course.code}</option>)}</select></label><label>Priority<select value={priority} onChange={e=>setPriority(e.target.value)}><option>high</option><option>medium</option><option>low</option></select></label><label>Expires<input required type="date" value={expires} onChange={e=>setExpires(e.target.value)}/></label><label className="wide">Message<textarea required value={body} onChange={e=>setBody(e.target.value)}/></label></div><div className="modalActions"><button type="button" onClick={close}>Cancel</button><button className="newButton" disabled={busy}>Publish securely</button></div></form></div>}
