"use client";
import { useEffect, useMemo, useState, type FormEvent } from "react";
import type { Announcement, Assignment, Event, Schedule } from "@campus-os/contracts";
import ScheduleTimeline from "./ScheduleTimeline";

const API=process.env.NEXT_PUBLIC_API_URL??"http://localhost:4000";
type Data={schedules:Schedule[];assignments:Assignment[];events:Event[];announcements:Announcement[]};
const initial:Data={schedules:[],assignments:[],events:[],announcements:[]};
const today=new Date(),iso=today.toISOString().slice(0,10),day=today.toLocaleDateString("en-US",{weekday:"long"});
const dateLabel=today.toLocaleDateString("en-US",{weekday:"long",month:"long",day:"numeric",year:"numeric"});
async function api<T>(path:string,options?:RequestInit):Promise<T>{const response=await fetch(API+path,{...options,headers:{"Content-Type":"application/json",...options?.headers}});const body=await response.json();if(!response.ok)throw new Error(body.error??"Request failed");return body}

export default function Home(){
 const [view,setView]=useState<"overview"|"schedule"|"announcements">("overview"),[data,setData]=useState(initial),[loading,setLoading]=useState(true),[error,setError]=useState(""),[toast,setToast]=useState(""),[showExpired,setShowExpired]=useState(false),[editor,setEditor]=useState<Announcement|null|"new">(null),[deleting,setDeleting]=useState<Announcement|null>(null);
 async function load(){setLoading(true);try{const [schedules,assignments,events,announcements]=await Promise.all([api<Schedule[]>("/schedules"),api<Assignment[]>("/assignments"),api<Event[]>("/events"),api<Announcement[]>("/announcements?include_expired=true")]);setData({schedules,assignments,events,announcements});setError("")}catch(e){setError((e as Error).message)}finally{setLoading(false)}}
 useEffect(()=>{load()},[]);useEffect(()=>{if(!toast)return;const timer=setTimeout(()=>setToast(""),2800);return()=>clearTimeout(timer)},[toast]);
 const nextClass=useMemo(()=>data.schedules.filter(x=>x.day===day).sort((a,b)=>a.start_time.localeCompare(b.start_time)).find(x=>x.end_time>today.toTimeString().slice(0,5))??data.schedules.filter(x=>x.day===day)[0],[data.schedules]);
 const dueSoon=useMemo(()=>data.assignments.filter(x=>!["submitted","graded"].includes(x.status)&&x.deadline>=iso).sort((a,b)=>a.deadline.localeCompare(b.deadline)).slice(0,3),[data.assignments]);
 const urgent=useMemo(()=>data.announcements.filter(x=>x.priority==="high"&&x.expires>=iso).sort((a,b)=>b.date.localeCompare(a.date))[0],[data.announcements]);
 const upcoming=useMemo(()=>data.events.filter(x=>x.date>=iso&&!["completed","cancelled"].includes(x.status)).sort((a,b)=>a.date.localeCompare(b.date)).slice(0,3),[data.events]);
 const notices=useMemo(()=>data.announcements.filter(x=>showExpired||x.expires>=iso).sort((a,b)=>b.date.localeCompare(a.date)),[data.announcements,showExpired]);
 async function save(value:Announcement){try{const isNew=editor==="new";const result=await api<Announcement>(`/announcements${isNew?"":`/${value.id}`}`,{method:isNew?"POST":"PATCH",body:JSON.stringify(isNew?value:{title:value.title,body:value.body,date:value.date,priority:value.priority,posted_by:value.posted_by,expires:value.expires})});setData(d=>({...d,announcements:isNew?[result,...d.announcements]:d.announcements.map(x=>x.id===result.id?result:x)}));setEditor(null);setToast(isNew?"Announcement published":"Announcement updated")}catch(e){setError((e as Error).message)}}
 async function remove(){if(!deleting)return;try{await api(`/announcements/${deleting.id}`,{method:"DELETE"});setData(d=>({...d,announcements:d.announcements.filter(x=>x.id!==deleting.id)}));setDeleting(null);setToast("Announcement deleted")}catch(e){setError((e as Error).message)}}
 const nav=[['overview','⌂','Overview'],['schedule','◷','Schedule'],['rooms','▦','Rooms'],['events','◇','Events'],['announcements','◉','Announcements'],['assignments','✓','Assignments']] as const;
 return <div className="portal"><aside><div className="logo"><span>C</span><b>CampusOS</b></div><p className="navLabel">MY CAMPUS</p><nav>{nav.map(([key,icon,label])=><button key={key} className={(key==="overview"&&view==="overview")||(key==="schedule"&&view==="schedule")||(key==="announcements"&&view==="announcements")?"active":""} onClick={()=>key==="overview"?setView("overview"):key==="schedule"?setView("schedule"):key==="announcements"?setView("announcements"):setToast(`${label} redesign is next`)}><i>{icon}</i>{label}{key==="announcements"&&<em>{data.announcements.filter(x=>x.priority==="high"&&x.expires>=iso).length}</em>}</button>)}</nav><button className="agent" onClick={()=>setToast("AI agent interface is coming next")}><span>✦</span><div><b>Ask CampusOS</b><small>AI campus assistant</small></div><i>→</i></button><div className="profile"><span>MS</span><div><b>My Student</b><small>Student workspace</small></div><button>•••</button></div></aside>
 <main><header><div><p className="crumb">CampusOS / <b>{view==="overview"?"Overview":view==="schedule"?"Schedule":"Announcements"}</b></p><h1>{view==="overview"?"Good morning, My Student":view==="schedule"?"Your campus schedule":"Campus announcements"}</h1><p>{view==="overview"?"Here’s what’s happening around your campus today.":view==="schedule"?"Plan classes by room, time, and instructor.":"Official updates, notices, and everything you shouldn’t miss."}</p></div><div className="context"><span>Today</span><b>{dateLabel}</b><i className={['Friday','Saturday'].includes(day)?'weekend':''}>{['Friday','Saturday'].includes(day)?'Weekend':'Campus day'}</i></div></header>
 {error&&<div className="error"><span>!</span><p><b>Something went wrong</b>{error}</p><button onClick={()=>setError("")}>×</button></div>}{toast&&<div className="toast"><span>✓</span>{toast}</div>}
 {loading?<Loading/>:view==="overview"?<Overview nextClass={nextClass} due={dueSoon} urgent={urgent} upcoming={upcoming} openNotices={()=>setView("announcements")}/>:view==="schedule"?<ScheduleTimeline/>:<Announcements items={notices} total={data.announcements.length} showExpired={showExpired} toggle={()=>setShowExpired(x=>!x)} add={()=>setEditor("new")} edit={setEditor} remove={setDeleting}/>} 
 </main>{editor&&<AnnouncementForm item={editor==="new"?undefined:editor} close={()=>setEditor(null)} save={save}/>} {deleting&&<Confirm item={deleting} close={()=>setDeleting(null)} confirm={remove}/>}</div>
}

function Overview({nextClass,due,urgent,upcoming,openNotices}:{nextClass?:Schedule;due:Assignment[];urgent?:Announcement;upcoming:Event[];openNotices():void}){return <><section className="hero"><div><span className="kicker">YOUR DAY AT A GLANCE</span><h2>Stay ahead,<br/><em>stress less.</em></h2><p>CampusOS brings your classes, work, and campus updates into one calm view.</p></div><div className="heroShape"><span>✦</span><i></i><b>{day.slice(0,3)}</b></div></section><div className="sectionTitle"><div><h2>Today’s overview</h2><p>Live information from across campus</p></div><span className="sync"><i/>Synced just now</span></div><section className="widgets">
 <article className="widget classWidget"><div className="widgetTop"><span className="icon purple">◷</span><small>NEXT CLASS</small></div>{nextClass?<><h3>{nextClass.course}</h3><p>{nextClass.title}</p><div className="classMeta"><span><small>TIME</small><b>{nextClass.start_time} – {nextClass.end_time}</b></span><span><small>ROOM</small><b>{nextClass.room}</b></span></div><div className="teacher"><span>{nextClass.instructor.split(' ').map(x=>x[0]).slice(0,2).join('')}</span><div><small>INSTRUCTOR</small><b>{nextClass.instructor}</b></div></div></>:<Empty text="No more classes today"/>}</article>
 <article className="widget dueWidget"><div className="widgetTop"><span className="icon coral">✓</span><small>DUE SOON</small><b>{due.length}</b></div><h3>Assignments</h3>{due.length?due.map(x=><div className="miniRow" key={x.id}><span><b>{x.title}</b><small>{x.course}</small></span><Due date={x.deadline}/></div>):<Empty text="Nothing due soon"/>}<button>View all assignments <span>→</span></button></article>
 <article className="widget noticeWidget"><div className="widgetTop"><span className="icon red">!</span><small>IMPORTANT NOTICE</small></div>{urgent?<><span className="priority">HIGH PRIORITY</span><h3>{urgent.title}</h3><p>{urgent.body}</p><div className="posted"><span>{urgent.posted_by.slice(0,2).toUpperCase()}</span><small>Posted by<br/><b>{urgent.posted_by}</b></small></div><button onClick={openNotices}>Read all announcements <span>→</span></button></>:<Empty text="No urgent notices"/>}</article>
 <article className="widget eventsWidget"><div className="widgetTop"><span className="icon mint">◇</span><small>COMING UP</small></div><h3>Upcoming events</h3>{upcoming.length?upcoming.map(x=><div className="eventRow" key={x.id}><span className="eventDate"><b>{new Date(x.date+'T00:00:00').getDate()}</b><small>{new Date(x.date+'T00:00:00').toLocaleDateString('en-US',{month:'short'})}</small></span><span><b>{x.name}</b><small>{x.start_time} · {x.venue}</small></span></div>):<Empty text="No upcoming events"/>}<button>Explore all events <span>→</span></button></article>
 </section></>}

function Announcements({items,total,showExpired,toggle,add,edit,remove}:{items:Announcement[];total:number;showExpired:boolean;toggle():void;add():void;edit(x:Announcement):void;remove(x:Announcement):void}){return <><div className="announcementHead"><div><span className="count">{items.length}</span><p>Showing current announcements<br/><small>{total-items.length} expired hidden</small></p></div><label className="toggle"><input type="checkbox" checked={showExpired} onChange={toggle}/><span/>Show expired</label><button className="newButton" onClick={add}>+ New announcement</button></div>{items.length?<section className="feed">{items.map(item=>{const expired=item.expires<iso;return <article className={`notice ${item.priority} ${expired?'expired':''}`} key={item.id}><div className="noticeAccent"/><div className="noticeBody"><div className="noticeTop"><span className={`priority ${item.priority}`}>{item.priority} priority</span><time>{new Date(item.date+'T00:00:00').toLocaleDateString('en-US',{month:'long',day:'numeric',year:'numeric'})}</time>{expired&&<span className="expiredTag">Expired</span>}</div><h2>{item.title}</h2><p>{item.body}</p><footer><div className="author"><span>{item.posted_by.split(' ').map(x=>x[0]).slice(0,2).join('')}</span><p><small>POSTED BY</small><b>{item.posted_by}</b></p></div><div className="noticeActions"><small>Expires {item.expires}</small><button onClick={()=>edit(item)}>Edit</button><button className="delete" onClick={()=>remove(item)}>Delete</button></div></footer></div></article>})}</section>:<div className="blank"><span>◉</span><h2>No announcements here</h2><p>Try showing expired notices or publish a new announcement.</p></div>}</>}

function AnnouncementForm({item,close,save}:{item?:Announcement;close():void;save(x:Announcement):void}){const [value,setValue]=useState<Announcement>(item??{id:`ann-${Date.now()}`,title:"",body:"",date:iso,priority:"medium",posted_by:"",expires:iso});function submit(e:FormEvent){e.preventDefault();save(value)}return <div className="backdrop" onMouseDown={e=>e.target===e.currentTarget&&close()}><form className="modal" onSubmit={submit}><div className="modalTitle"><div><small>{item?'UPDATE NOTICE':'PUBLISH NOTICE'}</small><h2>{item?'Edit announcement':'New announcement'}</h2></div><button type="button" onClick={close}>×</button></div><div className="formGrid"><label className="wide">Title<input required value={value.title} onChange={e=>setValue({...value,title:e.target.value})}/></label><label className="wide">Announcement body<textarea required value={value.body} onChange={e=>setValue({...value,body:e.target.value})}/></label><label>Priority<select value={value.priority} onChange={e=>setValue({...value,priority:e.target.value as Announcement['priority']})}><option>high</option><option>medium</option><option>low</option></select></label><label>Posted by<input required value={value.posted_by} onChange={e=>setValue({...value,posted_by:e.target.value})}/></label><label>Posted date<input type="date" required value={value.date} onChange={e=>setValue({...value,date:e.target.value})}/></label><label>Expires<input type="date" required value={value.expires} min={value.date} onChange={e=>setValue({...value,expires:e.target.value})}/></label></div><div className="modalActions"><button type="button" onClick={close}>Cancel</button><button className="newButton">{item?'Save changes':'Publish announcement'}</button></div></form></div>}
function Confirm({item,close,confirm}:{item:Announcement;close():void;confirm():void}){return <div className="backdrop"><div className="confirm"><span>!</span><h2>Delete announcement?</h2><p>“{item.title}” will be permanently removed.</p><div><button onClick={close}>Keep it</button><button className="deleteConfirm" onClick={confirm}>Delete announcement</button></div></div></div>}
function Loading(){return <div className="loading"><span/><span/><span/><p>Loading your campus…</p></div>};function Empty({text}:{text:string}){return <div className="empty">{text}</div>};function Due({date}:{date:string}){const days=Math.ceil((new Date(date+'T00:00:00').getTime()-new Date(iso+'T00:00:00').getTime())/864e5);return <em className={days<=2?'soon':''}>{days===0?'Today':days===1?'Tomorrow':`${days} days`}</em>}
