"use client";
import { useEffect, useState, type FormEvent, type ReactNode } from "react";
const API=process.env.NEXT_PUBLIC_API_URL??"http://localhost:4000";
type User={id:string;name:string;email:string;role:"student"|"teacher"|"cr"|"sr"|"admin";semester:string|null};
type Lecture={id:string;title:string;description:string;content_url:string;created_at:string};
type Course={id:string;code:string;title:string;semester:string;teacher:{name:string};lectures:Lecture[];_count:{enrollments:number}};
type Notice={id:string;title:string;body:string;semester:string;author_name:string;priority:string;expires:string};
type Workspace={user:User;courses:Course[];announcements:Notice[];admin_users:User[];metrics:{users:number;courses:number;rooms:number;events:number}};
async function request<T>(path:string,userId?:string,options?:RequestInit){const response=await fetch(API+path,{...options,headers:{"Content-Type":"application/json",...(userId?{"x-user-id":userId}:{}),...options?.headers}}),body=await response.json();if(!response.ok)throw new Error(body.error??"Request failed");return body as T}

export default function RoleDashboard({studentOverview}:{studentOverview:ReactNode}){
 const [users,setUsers]=useState<User[]>([]),[userId,setUserId]=useState("student-1"),[data,setData]=useState<Workspace|null>(null),[error,setError]=useState(""),[lectureCourse,setLectureCourse]=useState(""),[lecture,setLecture]=useState({title:"",description:"",content_url:""}),[notice,setNotice]=useState({title:"",body:"",semester:"Fall 2026",priority:"medium",expires:"2026-12-31"});
 async function load(id=userId){try{setData(await request<Workspace>("/workspace/me",id));setError("")}catch(e){setError((e as Error).message)}}
 useEffect(()=>{request<User[]>("/workspace/users").then(value=>{setUsers(value);const saved=localStorage.getItem("campusos-user");if(saved&&value.some(x=>x.id===saved))setUserId(saved)}).catch(e=>setError(e.message))},[]);
 useEffect(()=>{if(userId){localStorage.setItem("campusos-user",userId);void load(userId)}},[userId]);
 async function upload(e:FormEvent){e.preventDefault();try{await request(`/workspace/courses/${lectureCourse}/lectures`,userId,{method:"POST",body:JSON.stringify(lecture)});setLecture({title:"",description:"",content_url:""});await load()}catch(e){setError((e as Error).message)}}
 async function announce(e:FormEvent){e.preventDefault();try{await request("/workspace/announcements",userId,{method:"POST",body:JSON.stringify(notice)});setNotice({...notice,title:"",body:""});await load()}catch(e){setError((e as Error).message)}}
 async function changeRole(id:string,role:User["role"]){try{await request(`/workspace/users/${id}/role`,userId,{method:"PATCH",body:JSON.stringify({role})});await load()}catch(e){setError((e as Error).message)}}
 const user=data?.user;
 return <div className="roleWorkspace"><div className="roleBar"><div><small>ACTIVE WORKSPACE</small><b>{user?`${user.role.toUpperCase()} DASHBOARD`:"Loading dashboard"}</b></div><label>Demo account<select value={userId} onChange={e=>setUserId(e.target.value)}>{users.map(x=><option value={x.id} key={x.id}>{x.name} · {x.role.toUpperCase()}</option>)}</select></label></div>{error&&<div className="sectionError">{error}</div>}
 {user?.role==="student"&&<>{studentOverview}<ResourceArea data={data}/></>}
 {user?.role==="teacher"&&<><RoleHeading title="Teacher control room" text="Manage your assigned courses and publish lecture resources."/><ResourceArea data={data}/><form className="roleForm" onSubmit={upload}><h3>Upload lecture content</h3><select required value={lectureCourse} onChange={e=>setLectureCourse(e.target.value)}><option value="">Choose your course</option>{data?.courses.map(x=><option value={x.id} key={x.id}>{x.code} · {x.title}</option>)}</select><input required placeholder="Lecture title" value={lecture.title} onChange={e=>setLecture({...lecture,title:e.target.value})}/><input placeholder="Description" value={lecture.description} onChange={e=>setLecture({...lecture,description:e.target.value})}/><input required type="url" placeholder="Content URL (Drive, PDF, video…)" value={lecture.content_url} onChange={e=>setLecture({...lecture,content_url:e.target.value})}/><button className="newButton">Publish content</button></form></>}
 {(user?.role==="cr"||user?.role==="sr")&&<><RoleHeading title="CR/SR control room" text={`Announcements are restricted to ${user.semester}.`}/><form className="roleForm" onSubmit={announce}><h3>Semester announcement</h3><input required placeholder="Title" value={notice.title} onChange={e=>setNotice({...notice,title:e.target.value,semester:user.semester??notice.semester})}/><textarea required placeholder="Announcement" value={notice.body} onChange={e=>setNotice({...notice,body:e.target.value})}/><div><select value={notice.priority} onChange={e=>setNotice({...notice,priority:e.target.value})}><option>high</option><option>medium</option><option>low</option></select><input type="date" value={notice.expires} onChange={e=>setNotice({...notice,expires:e.target.value})}/></div><button className="newButton">Publish to {user.semester}</button></form><ResourceArea data={data}/></>}
 {user?.role==="admin"&&<><RoleHeading title="Administration control room" text="System-wide visibility across people, courses, spaces, and events."/><div className="adminMetrics"><Metric label="Users" value={data?.metrics.users??0}/><Metric label="Courses" value={data?.metrics.courses??0}/><Metric label="Rooms" value={data?.metrics.rooms??0}/><Metric label="Events" value={data?.metrics.events??0}/></div><section className="userControl"><h2>User access control</h2>{data?.admin_users.map(item=><div key={item.id}><span><b>{item.name}</b><small>{item.email} · {item.semester??"All semesters"}</small></span><select value={item.role} disabled={item.id===user.id} onChange={e=>changeRole(item.id,e.target.value as User["role"])}><option>student</option><option>teacher</option><option>cr</option><option>sr</option><option>admin</option></select></div>)}</section><ResourceArea data={data}/></>}
 </div>
}
function RoleHeading({title,text}:{title:string;text:string}){return <div className="roleHeading"><h2>{title}</h2><p>{text}</p></div>}
function Metric({label,value}:{label:string;value:number}){return <div><b>{value}</b><span>{label}</span></div>}
function ResourceArea({data}:{data:Workspace|null}){return <div className="resourceArea"><section><h2>Courses & lecture content</h2>{data?.courses.map(course=><article className="coursePanel" key={course.id}><header><div><b>{course.code}</b><h3>{course.title}</h3></div><span>{course.semester} · {course._count.enrollments} students</span></header>{course.lectures.length?course.lectures.map(item=><a href={item.content_url} target="_blank" rel="noreferrer" key={item.id}><b>{item.title}</b><small>{item.description||"Open lecture content"}</small></a>):<p>No lecture content yet.</p>}</article>)}</section><section><h2>Semester announcements</h2>{data?.announcements.map(item=><article className={`semesterNotice ${item.priority}`} key={item.id}><small>{item.semester} · {item.author_name}</small><h3>{item.title}</h3><p>{item.body}</p></article>)}</section></div>}
