ALTER TABLE "User" ADD COLUMN "section" TEXT;
ALTER TABLE "CourseOffering" ADD COLUMN "section" TEXT NOT NULL DEFAULT 'A';
DROP INDEX "CourseOffering_code_department_academic_year_semester_key";
CREATE UNIQUE INDEX "CourseOffering_code_department_academic_year_semester_section_key" ON "CourseOffering"("code", "department", "academic_year", "semester", "section");
ALTER TABLE "Schedule" ADD COLUMN "department" TEXT;
ALTER TABLE "Schedule" ADD COLUMN "academic_year" INTEGER;
ALTER TABLE "Schedule" ADD COLUMN "semester" INTEGER;
ALTER TABLE "Schedule" ADD COLUMN "teacher_id" TEXT;
ALTER TABLE "Booking" ADD COLUMN "user_id" TEXT;
ALTER TABLE "Booking" ADD COLUMN "status" TEXT NOT NULL DEFAULT 'approved';
ALTER TABLE "Event" ADD COLUMN "department" TEXT;
ALTER TABLE "Event" ADD COLUMN "academic_year" INTEGER;
ALTER TABLE "Event" ADD COLUMN "semester" INTEGER;
ALTER TABLE "Announcement" ADD COLUMN "department" TEXT;
ALTER TABLE "Announcement" ADD COLUMN "academic_year" INTEGER;
ALTER TABLE "Announcement" ADD COLUMN "semester" INTEGER;
ALTER TABLE "Announcement" ADD COLUMN "section" TEXT;
ALTER TABLE "Announcement" ADD COLUMN "course" TEXT;
ALTER TABLE "Announcement" ADD COLUMN "author_id" TEXT;
ALTER TABLE "Assignment" ADD COLUMN "department" TEXT;
ALTER TABLE "Assignment" ADD COLUMN "academic_year" INTEGER;
ALTER TABLE "Assignment" ADD COLUMN "semester" INTEGER;
ALTER TABLE "Assignment" ADD COLUMN "teacher_id" TEXT;
UPDATE "User" SET "role" = 'cr' WHERE "role" = 'representative';
ALTER TABLE "CohortAnnouncement" ADD COLUMN "section" TEXT;
