CREATE TABLE "Schedule" ("id" TEXT NOT NULL PRIMARY KEY, "course" TEXT NOT NULL, "title" TEXT NOT NULL, "day" TEXT NOT NULL, "start_time" TEXT NOT NULL, "end_time" TEXT NOT NULL, "room" TEXT NOT NULL, "instructor" TEXT NOT NULL, "section" TEXT NOT NULL);
CREATE INDEX "Schedule_day_start_time_idx" ON "Schedule"("day", "start_time");
CREATE INDEX "Schedule_course_idx" ON "Schedule"("course");
CREATE TABLE "Room" ("id" TEXT NOT NULL PRIMARY KEY, "room_number" TEXT NOT NULL, "type" TEXT NOT NULL, "capacity" INTEGER NOT NULL, "equipment" TEXT NOT NULL, "floor" INTEGER NOT NULL, "status" TEXT NOT NULL);
CREATE UNIQUE INDEX "Room_room_number_key" ON "Room"("room_number");
CREATE INDEX "Room_status_capacity_idx" ON "Room"("status", "capacity");
CREATE TABLE "Booking" ("booking_id" TEXT NOT NULL PRIMARY KEY, "booked_by" TEXT NOT NULL, "date" TEXT NOT NULL, "start_time" TEXT NOT NULL, "end_time" TEXT NOT NULL, "purpose" TEXT NOT NULL, "room_id" TEXT NOT NULL, CONSTRAINT "Booking_room_id_fkey" FOREIGN KEY ("room_id") REFERENCES "Room" ("id") ON DELETE CASCADE ON UPDATE CASCADE);
CREATE INDEX "Booking_room_id_date_start_time_end_time_idx" ON "Booking"("room_id", "date", "start_time", "end_time");
CREATE TABLE "Event" ("id" TEXT NOT NULL PRIMARY KEY, "name" TEXT NOT NULL, "description" TEXT NOT NULL, "date" TEXT NOT NULL, "start_time" TEXT NOT NULL, "end_time" TEXT NOT NULL, "end_date" TEXT NOT NULL, "venue" TEXT NOT NULL, "organizer" TEXT NOT NULL, "capacity" INTEGER NOT NULL, "registered" INTEGER NOT NULL, "status" TEXT NOT NULL);
CREATE INDEX "Event_date_start_time_idx" ON "Event"("date", "start_time");
CREATE INDEX "Event_status_idx" ON "Event"("status");
CREATE TABLE "Registration" ("id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, "student_id" TEXT NOT NULL, "name" TEXT NOT NULL, "event_id" TEXT NOT NULL, CONSTRAINT "Registration_event_id_fkey" FOREIGN KEY ("event_id") REFERENCES "Event" ("id") ON DELETE CASCADE ON UPDATE CASCADE);
CREATE UNIQUE INDEX "Registration_event_id_student_id_key" ON "Registration"("event_id", "student_id");
CREATE TABLE "Announcement" ("id" TEXT NOT NULL PRIMARY KEY, "title" TEXT NOT NULL, "body" TEXT NOT NULL, "date" TEXT NOT NULL, "priority" TEXT NOT NULL, "posted_by" TEXT NOT NULL, "expires" TEXT NOT NULL);
CREATE INDEX "Announcement_date_idx" ON "Announcement"("date");
CREATE INDEX "Announcement_priority_idx" ON "Announcement"("priority");
CREATE TABLE "Assignment" ("id" TEXT NOT NULL PRIMARY KEY, "course" TEXT NOT NULL, "course_title" TEXT NOT NULL, "title" TEXT NOT NULL, "description" TEXT NOT NULL, "assigned_date" TEXT NOT NULL, "deadline" TEXT NOT NULL, "submission_platform" TEXT NOT NULL, "status" TEXT NOT NULL, "marks" REAL NOT NULL);
CREATE INDEX "Assignment_deadline_idx" ON "Assignment"("deadline");
CREATE INDEX "Assignment_course_status_idx" ON "Assignment"("course", "status");
